package maybego

import "fmt"

type Opcode struct {
	offset uint
	disasm string
}

type Disasm struct {
	file         *[]byte
	current_addr uint
	lines        []Opcode
	opcodes      [256]func() string
	cbOps        [256]func() string
}

func NewDisasm() *Disasm {
	disasm := &Disasm{current_addr: 0x0}
	disasm.opcodes = [256]func() string{
		func() string { disasm.current_addr++; return "nop\n" },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
	}

	return disasm
}

func (dis *Disasm) SetFile(file *[]byte) {
	dis.file = file
}

func (dis *Disasm) Disassemble() {
	for dis.current_addr < uint(len(*dis.file)) {
		opc := (*dis.file)[dis.current_addr]
		fmt.Printf("0x%X\t| %s", dis.current_addr, dis.opcodes[opc]())
	}
}

func (dis *Disasm) not_implemented() string {
	dis.current_addr++
	return "not implemented yet!\n"
}
