package maybego

import "fmt"

type Opcode struct {
	offset uint
	disasm string
}

type Disasm struct {
	file         *[]byte
	current_addr uint
	lines        []Opcode
	opcodes      [256]func() string
	cbOps        [256]func() string
}

func NewDisasm() *Disasm {
	disasm := &Disasm{current_addr: 0x0}
	disasm.opcodes = [256]func() string{
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
		func() string { return disasm.not_implemented() },
	}

	return disasm
}

func (dis *Disasm) SetFile(file *[]byte) {
	dis.file = file
}

func (dis *Disasm) Disassemble() {
	for _, opc := range /*uint(len(dis.file)) */ *dis.file {
		// opc := (*dis.file)[dis.current_addr]
		// dis.lines[]&Opcode{}
		fmt.Printf("%s", dis.opcodes[opc]())
	}
	fmt.Printf("finished at %x", dis.current_addr)
}

func (dis *Disasm) not_implemented() string {
	dis.current_addr++
	return "not implemented yet!\n"
}
